# Generated by Django 3.2.9 on 2022-03-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('students_code', models.CharField(max_length=4)),
                ('mobile', models.CharField(max_length=15)),
                ('sd', models.CharField(max_length=10)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.position')),
            ],
        ),
    ]
