# Generated by Django 3.2.9 on 2022-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sd',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
